#!/usr/bin/env node
/**
 * SSL Termination Proxy
 *
 * Listens on HTTPS and forwards every request to the local HTTP app.
 * Zero npm dependencies — uses only built-in Node.js modules.
 *
 * Env vars (read from process.env — source your .env before starting):
 *   HTTPS_PORT  — HTTPS port to bind (default 9443)
 *   HTTP_PORT   — upstream HTTP app port (default 9393)
 *
 * Certificates:
 *   certs/server.key   private key  (generated by run_ssl_proxy.sh)
 *   certs/server.crt   certificate  (generated by run_ssl_proxy.sh)
 */

import https from 'node:https';
import http  from 'node:http';
import fs    from 'node:fs';
import path  from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname  = path.dirname(fileURLToPath(import.meta.url));

const HTTPS_PORT = parseInt(process.env.HTTPS_PORT ?? '9443', 10);
const HTTP_PORT  = parseInt(process.env.HTTP_PORT  ?? '9393', 10);
const BIND_HOST  = '127.0.0.1';

const certsDir = path.join(__dirname, 'certs');

let tlsOptions;
try {
    tlsOptions = {
        key:  fs.readFileSync(path.join(certsDir, 'server.key')),
        cert: fs.readFileSync(path.join(certsDir, 'server.crt')),
    };
} catch (err) {
    console.error(`[ssl-proxy] Cannot read certificates from ${certsDir}:`);
    console.error(`           ${err.message}`);
    console.error('           Run  ./run_ssl_proxy.sh  to generate them automatically.');
    process.exit(1);
}

const server = https.createServer(tlsOptions, (req, res) => {
    const proxyOptions = {
        hostname: BIND_HOST,
        port:     HTTP_PORT,
        path:     req.url,
        method:   req.method,
        headers: {
            ...req.headers,
            host:                `${BIND_HOST}:${HTTP_PORT}`,
            'x-forwarded-proto': 'https',
            'x-forwarded-for':   req.socket.remoteAddress ?? BIND_HOST,
        },
    };

    const proxyReq = http.request(proxyOptions, (proxyRes) => {
        res.writeHead(proxyRes.statusCode, proxyRes.headers);
        proxyRes.pipe(res, { end: true });
    });

    proxyReq.on('error', (err) => {
        if (!res.headersSent) res.writeHead(502);
        res.end(`Upstream error: ${err.message}`);
    });

    req.pipe(proxyReq, { end: true });
});

server.on('error', (err) => {
    console.error('[ssl-proxy] Fatal:', err.message);
    process.exit(1);
});

server.listen(HTTPS_PORT, BIND_HOST, () => {
    console.log(`[ssl-proxy] https://${BIND_HOST}:${HTTPS_PORT}  →  http://${BIND_HOST}:${HTTP_PORT}`);
});
