name: "CI-main"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Deps
        run: npm install

      - name: Test
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_USER_ID: ${{ secrets.SPOTIFY_USER_ID }}
          SPOTIFY_PLAYLIST_PREFIX: ${{ secrets.SPOTIFY_PLAYLIST_PREFIX }}
          SPOTIFY_CALLBACK_ENDPOINT: ${{ secrets.SPOTIFY_CALLBACK_ENDPOINT }}
          SPOTIFY_PLAYLIST_MAP: ${{ secrets.SPOTIFY_PLAYLIST_MAP }}
          SPOTIFY_USER_OAUTH: ${{ secrets.SPOTIFY_USER_OAUTH }}
          HTTP_PORT: ${{ secrets.HTTP_PORT }}
        run: npm test
