name: "CI-master"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Deps
        run: npm install

      - name: Test
        run: npm test
